In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel("Fastbase_business_contacts_excel_699_HVVPQG.xlsx")

In [3]:
df

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,EMAIL,First EMAIL,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Benjamin Yarish,Benjamin,Yarish,"Chief, Chief Information Officer Enterprise Re...",Information Technology and Services,Air Force Civilian Service,bjyarish@yahoo.com,bjyarish@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Waseem Abou-Marie,Waseem,Abou-Marie,"Group Chief Information Officer - Middle East,...",Information Technology and Services,Ge,waseemmarie@gmail.com,waseemmarie@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4062,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Automotive,Ford Motor Company,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4064,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4065,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.isnull().sum()

FULL NAME              0
First Name             0
Last Name              0
JOB TITLE              0
COMPANY CATEGORY     125
COMPANY NAME           0
EMAIL                  0
First EMAIL            0
Second Email        2185
Third               3445
Fourth              3844
Unnamed: 11         3995
Unnamed: 12         4034
Unnamed: 13         4056
Unnamed: 14         4062
Unnamed: 15         4065
Unnamed: 16         4066
dtype: int64

In [26]:
len(df['COMPANY CATEGORY'].unique())

121

In [25]:
l=df['COMPANY CATEGORY'].unique()
for i in l:
    print(i)

Human Resources
Information Technology and Services
Higher Education
Food Production
Marketing and Advertising
Government and Federal
Writing and Editing
Hospital Health Care
Hospitality
Investment Banking
Financial Services
Military
International Development
Restaurants
Transportation
Media and Telecommunications
Outsourcing/Offshoring
Education Management
Aerospace and Defense
Renewables Environment
Airlines/Aviation
nan
Insurance
Professional Training Coaching
Non-Profit Organization Management
Internet
Construction
Computer Software
Computer Networking
Law Practice
Pharmaceuticals
Leisure, Travel, Tourism
Gambling Casinos
Management Consulting
Sporting Goods
Music
Executive Office
Supply Chain
Medical Devices
Facilities Services
Oil Energy
E-Learning
Investment Management
Consumer Electronics
Apparel Fashion
Telecommunications
Security and Investigations
Public Safety
Research
Information Services
Computer Hardware
Banking
Manufacturing
Retail
Environmental Services
Health, Wellness and Fitness
Consumer Services
Consumer Goods
Wholesale
Machinery
Primary/Secondary Education
Luxury Goods Jewelry
Public Policy
Accounting
Events Services
Program Development
Legal Services
Biotechnology
Computer Network Security
Chemicals
Computer Games
Market Research
Mining Metals
Civil Engineering
Farming
Sports
Real Estate
Semiconductors
Food Beverages
Broadcast Media
Energy and Mining and raw Materials
Textiles
Maritime
Medical Practice
Staffing and Recruiting
International Affairs
Publishing
Entertainment
Wireless
Packaging and Containers
Cosmetics
Business Supplies and Equipment
Commercial Real Estate
Graphic Design
Warehousing
Individual Family Services
Media Production
Glass, Ceramics, Concrete
Paper Forest Products
Alternative Medicine
Public Relations and Communications
Veterinary
Animation
Law Enforcement
Furniture
Recreational Facilities and Services
Capital Markets
Online Media
Supermarkets
Architecture Planning
Venture Capital Private Equity
Newspapers
Railroad Manufacture
Religious Institutions
Nanotechnology
Design
Printing
Judiciary
Ranching
Photography
Fine Art

In [23]:
df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Government Administration'],'Government and Federal')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Defense Space'],'Aerospace and Defense')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Aviation Aerospace'],'Aerospace and Defense')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Utilities'],'Media and Telecommunications')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Logistics and Supply Chain'],'Supply Chain')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Building Materials'],'Energy and Mining and raw Materials')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Electrical/Electronic Manufacturing'],'Manufacturing')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Automotive'],'Transportation')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Transportation/Trucking/Railroad'],'Transportation')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Package/Freight Delivery'],'Supply Chain')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Industrial Automation'],'Manufacturing')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Import and Export'],'Supply Chain')

df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['International Trade and Development'],'International Development')


df['COMPANY CATEGORY'] = df['COMPANY CATEGORY'].replace(['Mechanical or Industrial Engineering'],'Manufacturing')

In [68]:
df

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Benjamin Yarish,Benjamin,Yarish,"Chief, Chief Information Officer Enterprise Re...",Information Technology and Services,Air Force Civilian Service,bjyarish@yahoo.com,bjyarish@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Waseem Abou-Marie,Waseem,Abou-Marie,"Group Chief Information Officer - Middle East,...",Information Technology and Services,Ge,waseemmarie@gmail.com,waseemmarie@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4062,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4064,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4065,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df1=df

In [62]:
df1.rename(columns = {'First EMAIL':'First'}, inplace = True)

In [50]:
discard = ["@gmail.com"]

In [51]:
#df1.drop(df1[df1['First EMAIL'] == 500].index, inplace = True)
df1=df1[~df1.First.str.contains('|'.join(discard))]

In [56]:
df1

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Benjamin Yarish,Benjamin,Yarish,"Chief, Chief Information Officer Enterprise Re...",Information Technology and Services,Air Force Civilian Service,bjyarish@yahoo.com,bjyarish@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Waseem Abou-Marie,Waseem,Abou-Marie,"Group Chief Information Officer - Middle East,...",Information Technology and Services,Ge,waseemmarie@gmail.com,waseemmarie@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4062,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4064,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4065,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
discard1 = ["@yahoo.com"]

In [58]:
df1=df1[~df1.First.str.contains('|'.join(discard1))]

In [63]:
df1

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Benjamin Yarish,Benjamin,Yarish,"Chief, Chief Information Officer Enterprise Re...",Information Technology and Services,Air Force Civilian Service,bjyarish@yahoo.com,bjyarish@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Waseem Abou-Marie,Waseem,Abou-Marie,"Group Chief Information Officer - Middle East,...",Information Technology and Services,Ge,waseemmarie@gmail.com,waseemmarie@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4062,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4064,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4065,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
discard2 = ["@hotmail.com"]

In [65]:
df1=df1[df1.First.str.contains('|'.join(discard2))]

In [66]:
df1

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
47,Rob Sprout,Rob,Sprout,"Da Chief Information Officer and G6 Chief, Int...",Information Technology and Services,Us Army,robsprout@hotmail.com,robsprout@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Eugene Walker,Eugene,Walker,Chief Information Officer Ecosystem Products a...,Computer Software,Accenture,eugene.r.walker@hotmail.com,eugene.r.walker@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Sandra Roitman,Sandra,Roitman,Vice President and Chile Chief Information Off...,Information Technology and Services,Metlife,roitmans@hotmail.com,roitmans@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Gary Pratt,Gary,Pratt,Chief Information Officer,Higher Education,Kansas State University,"gary.pratt@hotmail.com, gary.pratt@earthlink.net",gary.pratt@hotmail.com,gary.pratt@earthlink.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Aparna Kurada,Aparna,Kurada,Chief Information Officer Lead For The Cogniti...,Information Technology and Services,Ibm,akurada@hotmail.com,akurada@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930,Latressa Fulton,Latressa,Fulton,"Senior Advisor, Office of Chief Information Of...",Government and Federal,New York City Housing Authority (Nycha),latressaf@hotmail.com,latressaf@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3958,Eric Phillips,Eric,Phillips,Chief Information Officer - North America Oper...,Financial Services,Bmo Financial Group,ewphillips15@hotmail.com,ewphillips15@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4000,Donald Patra,Donald,Patra,"Chief Information Officer, Us, Canada, Latam",Financial Services,Hsbc,donaldpatra@hotmail.com,donaldpatra@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,Veena Rajkumar,Veena,Rajkumar,Global Learning and Development Manager,Professional Training Coaching,Western Digital,veena623@hotmail.com,veena623@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4029,Jill Johnson,Jill,Johnson,Learning and Development Manager and Coach,Professional Training Coaching,The Boston Consulting Group (Bcg),jmstasell@hotmail.com,jmstasell@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
file_name = 'Working2hotmail.xlsx'
df1.to_excel(file_name)

In [71]:
df10=pd.read_excel("C:/Users/admin/Desktop/new/working1.xlsx")

In [106]:
df10

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,PpgIndustries,ppgindustries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,UcDavis,ucdavis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,TysonFoods,tysonfoods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jill Cook,Jill,Cook,Senior Learning and Development Specialist,Human Resources,Target,Target,target,jill.cook@target.com,jill.cook@target.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patrick Dineen,Patrick,Dineen,Interim Global Chief Information Officer,Marketing and Advertising,Nielsen,Nielsen,nielsen,"patrick.dineen@nielsen.com, patdineenfamily@ya...",patrick.dineen@nielsen.com,patdineenfamily@yahoo.com,pdiddy1286@erols.com,pdiddy@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,FordMotorCompany,fordmotorcompany,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,UniversityOfArkansasSystem,universityofarkansassystem,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,TexasTechUniversity,texastechuniversity,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,Intertek,intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3489,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,CityOfPhoenix,cityofphoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
df10.dtypes

FULL NAME           object
First Name          object
Last Name           object
JOB TITLE           object
COMPANY CATEGORY    object
COMPANY NAME        object
COMA                object
COMPANYD            object
EMAIL               object
First               object
Second Email        object
Third               object
Fourth              object
Unnamed: 11         object
Unnamed: 12         object
Unnamed: 13         object
Unnamed: 14         object
Unnamed: 15         object
Unnamed: 16         object
dtype: object

In [107]:
import re

In [105]:
text= "tibor.szikszai@bankofthewest.com"
text.re.findall(pattern,text)

#l=re.findall(pattern,text)

AttributeError: 'str' object has no attribute 're'

In [101]:
l[0]

'bankofthewest'

In [ ]:
df["exists"] = df.drop("First", 1).isin(df["First"]).any(1)

In [119]:
a='sachin19566@gmail.com'
a[-5:-8:-1][::-1]

'ail'

In [125]:
def find_value_column(row):
    return row.First[-5:-8:-1][::-1] in row.COMPANYD

df11=df10[df10.apply(find_value_column, axis=1)]

In [126]:
df11

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,PpgIndustries,ppgindustries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,TysonFoods,tysonfoods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jill Cook,Jill,Cook,Senior Learning and Development Specialist,Human Resources,Target,Target,target,jill.cook@target.com,jill.cook@target.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patrick Dineen,Patrick,Dineen,Interim Global Chief Information Officer,Marketing and Advertising,Nielsen,Nielsen,nielsen,"patrick.dineen@nielsen.com, patdineenfamily@ya...",patrick.dineen@nielsen.com,patdineenfamily@yahoo.com,pdiddy1286@erols.com,pdiddy@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN
7,Ron Double,Ron,Double,Chief Information Officer at Parkview Health,Hospital Health Care,Parkview Health,ParkviewHealth,parkviewhealth,ron.double@parkview.com,ron.double@parkview.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3480,Mindy Simon,Mindy,Simon,Chief Information Officer Global Business and ...,Consumer Goods,Conagra Foods,ConagraFoods,conagrafoods,mindy.simon@conagrafoods.com,mindy.simon@conagrafoods.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,Joe Dumara,Joe,Dumara,Chief Information Officer,Transportation,John Deere Agri Services,JohnDeereAgriServices,johndeereagriservices,"joe.dumara@deere.com, jdumara@deere.com",joe.dumara@deere.com,jdumara@deere.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3485,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,FordMotorCompany,fordmotorcompany,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,Intertek,intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3489,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,CityOfPhoenix,cityofphoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
file_name = 'matched.xlsx'
df11.to_excel(file_name)

In [128]:
def find_value_column(row):
    return row.First[-5:-8:-1][::-1] in row.COMPANYD

df12=df10[~df10.apply(find_value_column, axis=1)]

In [129]:
df12

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
1,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,UcDavis,ucdavis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Jim Onalfo,Jim,Onalfo,Chief Information Officer,Government and Federal,Nypd,Nypd,nypd,jonalfo@aol.com,jonalfo@aol.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Katherine Noyes,Katherine,Noyes,"Senior Writer, Manager, Chief Information Offi...",Writing and Editing,Deloitte,Deloitte,deloitte,"katherine_noyes@idg.com, noyesk@linux.com, noy...",katherine_noyes@idg.com,noyesk@linux.com,noyes@conwaycorp.net,knoyes@idgcommunications.com,NaN,NaN,NaN,NaN,NaN,NaN
15,Stacy Whitmore,Stacy,Whitmore,Learning and Development Specialist,Restaurants,"Arby`S Restaurant Group, Inc.","Arby`SRestaurantGroup,Inc.","arby`srestaurantgroup,inc.",swhitmore@arbys.com,swhitmore@arbys.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Dale Jablonsky,Dale,Jablonsky,Chief Information Officer Advisory Director,Government and Federal,Kpmg,Kpmg,kpmg,"dale_jablonsky@calpers.ca.gov, djablons75@gmai...",dale_jablonsky@calpers.ca.gov,djablons75@gmail.com,djablonsky@aol.com,dale.jablonsky@performtechnology.com,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3481,Dorian Stevens,Dorian,Stevens,Head of Chief Information Officer Pmo,Information Technology and Services,Radisson Hotel Group,RadissonHotelGroup,radissonhotelgroup,"dorianstevens@eurofins.com, dorianstevens@gmai...",dorianstevens@eurofins.com,dorianstevens@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3483,Jean-Pierre Champigny,Jean-Pierre,Champigny,Chief Information Officer,Banking,Cic,Cic,cic,jpchampigny@cicny.com,jpchampigny@cicny.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3484,Ric Hunter,Ric,Hunter,"Communications Specialist, Office of The Chief...",Higher Education,The Ohio State University,TheOhioStateUniversity,theohiostateuniversity,hunter.346@osu.edu,hunter.346@osu.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,UniversityOfArkansasSystem,universityofarkansassystem,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,TexasTechUniversity,texastechuniversity,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
file_name = 'Notmatched.xlsx'
df12.to_excel(file_name)

In [2]:
df20=pd.read_excel("C:/Users/admin/Desktop/new/working1.xlsx")

In [3]:
df20

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Human Resources,Ppg Industries,PpgIndustries,ppgindustries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Higher Education,Uc Davis,UcDavis,ucdavis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,TysonFoods,tysonfoods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jill Cook,Jill,Cook,Senior Learning and Development Specialist,Human Resources,Target,Target,target,jill.cook@target.com,jill.cook@target.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patrick Dineen,Patrick,Dineen,Interim Global Chief Information Officer,Marketing and Advertising,Nielsen,Nielsen,nielsen,"patrick.dineen@nielsen.com, patdineenfamily@ya...",patrick.dineen@nielsen.com,patdineenfamily@yahoo.com,pdiddy1286@erols.com,pdiddy@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,FordMotorCompany,fordmotorcompany,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Information Technology and Services,University Of Arkansas System,UniversityOfArkansasSystem,universityofarkansassystem,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,Sam Segran,Sam,Segran,Chief Information Officer,Education Management,Texas Tech University,TexasTechUniversity,texastechuniversity,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,Diane Hanson,Diane,Hanson,Learning and Development Manager,Human Resources,Intertek,Intertek,intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3489,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Information Technology and Services,City Of Phoenix,CityOfPhoenix,cityofphoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Human Resources'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Information Technology and Services'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Higher Education'],'Education')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Education Management'],'Education')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Writing and Editing'],'Marketing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Hospital Health Care'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Military'],'Aerospace and Defense')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Investment Banking'],'Finance')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Financial Services'],'Finance')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Renewables Environment'],'Environment and Renewables')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Airlines/Aviation'],'Transportation')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Restaurants'],'Hospitality ')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Outsourcing/Offshoring'],'Supply Chain')


df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Renewables Environment'],'Energy and Mining and Raw Materials')


df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Professional Training Coaching'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Non-Profit Organization Management'],'Non-Profit')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Internet'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Construction'],'Manufacturing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Computer Software'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Computer Networking'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Law Practice'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Pharmaceuticals'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Leisure, Travel, Tourism'],'Hospitality ')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Gambling Casinos'],'Hospitality')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Management Consulting'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Sporting Goods'],'Retail')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Executive Office'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Facilities Services'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Medical Devices'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Oil Energy'],'Energy and Mining and Raw Materials')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['E-Learning'],'Technology;Education')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Investment Management'],'Finance')



df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Consumer Electronics'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Apparel Fashion'],'Retail')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Telecommunications'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Security and Investigations'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Public Safety'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Accounting'],'Finance')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Research'],'Professional Services')


df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Information Services'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Computer Hardware'],'Technology')
df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Banking'],'Finance')
df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Environmental Services'],'Environment and Renewables')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Health, Wellness and Fitness'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Wholesale'],'Supply Chain')


df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Machinery'],'Manufacturing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Primary/Secondary Education'],'Education')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Luxury Goods Jewelry'],'Retail')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Public Policy'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Events Services'],'Entertainment')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Program Development'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Legal Services'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Computer Network Security'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Biotechnology'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Chemicals'],'Energy and Mining and Raw Materials')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Computer Games'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Market Research'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Mining Metals'],'Energy and Mining and Raw Materials')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Civil Engineering'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Farming'],'Environment and Renewables')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Sports'],'Entertainment')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Real Estate'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Semiconductors'],'Manufacturing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Broadcast Media'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Textiles'],'Manufacturing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Maritime'],'Aerospace and Defense')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Medical Practice'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Staffing and Recruiting'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['International Affairs'],'International Development')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Publishing'],'Media and Telecommunications')
df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Wireless'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Packaging and Containers'],'Supply Chain')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Cosmetics'],'Retail')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Business Supplies and Equipment'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Commercial Real Estate'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Graphic Design'],'Marketing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Warehousing'],' Supply Chain')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Individual Family Services'],'Education')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Media Production'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Glass, Ceramics, Concrete'],'Energy and Mining and Raw Materials')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Paper Forest Products'],'Environment and Renewables')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Public Relations and Communications'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Veterinary'],'Healthcare')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Animation'],'Technology')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Law Enforcement'],'Government and Federal')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Furniture'],'Manufacturing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Recreational Facilities and Services'],'Entertainment')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Capital Markets'],'Finance')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Online Media'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Supermarkets'],'Retail')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Architecture Planning'],'Professional Services')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Venture Capital Private Equity'],'Finance')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Newspapers'],'Media and Telecommunications')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Railroad Manufacture'],'Transportation')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Religious Institutions'],'Non-Profit')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Design'],'Marketing')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Judiciary'],'Government and Federal')

df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace(['Photography'],'Entertainment')

#df10['COMPANY CATEGORY'] = dfs10['COMPANY CATEGORY'].replace(['Cosmetics'],'Retail')

In [112]:
df20

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Linda Iasouvanh,Linda,Iasouvanh,Learning and Development Manager - Anz,Professional Services,Ppg Industries,PpgIndustries,ppgindustries,liasouvanh@ppg.com,liasouvanh@ppg.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Education,Uc Davis,UcDavis,ucdavis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Food Production,Tyson Foods,TysonFoods,tysonfoods,jeri.dunn@tyson.com,jeri.dunn@tyson.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jill Cook,Jill,Cook,Senior Learning and Development Specialist,Professional Services,Target,Target,target,jill.cook@target.com,jill.cook@target.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patrick Dineen,Patrick,Dineen,Interim Global Chief Information Officer,Marketing and Advertising,Nielsen,Nielsen,nielsen,"patrick.dineen@nielsen.com, patdineenfamily@ya...",patrick.dineen@nielsen.com,patdineenfamily@yahoo.com,pdiddy1286@erols.com,pdiddy@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Transportation,Ford Motor Company,FordMotorCompany,fordmotorcompany,"ndaman@ford.com, nadasdaman@yahoo.com",ndaman@ford.com,nadasdaman@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Technology,University Of Arkansas System,UniversityOfArkansasSystem,universityofarkansassystem,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,Sam Segran,Sam,Segran,Chief Information Officer,Education,Texas Tech University,TexasTechUniversity,texastechuniversity,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,Diane Hanson,Diane,Hanson,Learning and Development Manager,Professional Services,Intertek,Intertek,intertek,"diane.hanson@intertek.com, dihanson@hotmail.com",diane.hanson@intertek.com,dihanson@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3489,Debbie Dertz,Debbie,Dertz,Deputy Chief Information Officer at City of Ph...,Technology,City Of Phoenix,CityOfPhoenix,cityofphoenix,debbie.dertz@phoenix.gov,debbie.dertz@phoenix.gov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
l=df20['COMPANY CATEGORY'].unique()
for i in l:
    #if i=='Fine-Arts':
    print(i)

Professional Services
Education
Food Production
Marketing and Advertising
Government and Federal
Marketing
Healthcare
Hospitality
Finance
Aerospace and Defense
International Development
Hospitality
Transportation
Media and Telecommunications
Technology
Supply Chain
Environment and Renewables
nan
Insurance
Non-Profit
Manufacturing
Retail
Energy and Mining and Raw Materials
Technology;Education
Consumer Goods
Entertainment
Consumer Services
Food Beverages
Energy and Mining and raw Materials
Printing

In [110]:
df20['COMPANY CATEGORY'] = df20['COMPANY CATEGORY'].replace([' Supply Chain'],'Supply Chain')

In [117]:
def find_value_column(row):
    return row.First[-5:-8:-1][::-1] in row.COMPANYD

df22=df20[~df20.apply(find_value_column, axis=1)]

In [118]:
df22

,FULL NAME,First Name,Last Name,JOB TITLE,COMPANY CATEGORY,COMPANY NAME,COMA,COMPANYD,EMAIL,First,Second Email,Third,Fourth,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
1,Meggan Levitt,Meggan,Levitt,Assistant Vice Provost and Associate Chief Inf...,Education,Uc Davis,UcDavis,ucdavis,"mlevitt@berkeley.edu, megganlevitt@gmail.com",mlevitt@berkeley.edu,megganlevitt@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Jim Onalfo,Jim,Onalfo,Chief Information Officer,Government and Federal,Nypd,Nypd,nypd,jonalfo@aol.com,jonalfo@aol.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Katherine Noyes,Katherine,Noyes,"Senior Writer, Manager, Chief Information Offi...",Marketing,Deloitte,Deloitte,deloitte,"katherine_noyes@idg.com, noyesk@linux.com, noy...",katherine_noyes@idg.com,noyesk@linux.com,noyes@conwaycorp.net,knoyes@idgcommunications.com,NaN,NaN,NaN,NaN,NaN,NaN
15,Stacy Whitmore,Stacy,Whitmore,Learning and Development Specialist,Hospitality,"Arby`S Restaurant Group, Inc.","Arby`SRestaurantGroup,Inc.","arby`srestaurantgroup,inc.",swhitmore@arbys.com,swhitmore@arbys.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Dale Jablonsky,Dale,Jablonsky,Chief Information Officer Advisory Director,Government and Federal,Kpmg,Kpmg,kpmg,"dale_jablonsky@calpers.ca.gov, djablons75@gmai...",dale_jablonsky@calpers.ca.gov,djablons75@gmail.com,djablonsky@aol.com,dale.jablonsky@performtechnology.com,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3481,Dorian Stevens,Dorian,Stevens,Head of Chief Information Officer Pmo,Technology,Radisson Hotel Group,RadissonHotelGroup,radissonhotelgroup,"dorianstevens@eurofins.com, dorianstevens@gmai...",dorianstevens@eurofins.com,dorianstevens@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3483,Jean-Pierre Champigny,Jean-Pierre,Champigny,Chief Information Officer,Finance,Cic,Cic,cic,jpchampigny@cicny.com,jpchampigny@cicny.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3484,Ric Hunter,Ric,Hunter,"Communications Specialist, Office of The Chief...",Education,The Ohio State University,TheOhioStateUniversity,theohiostateuniversity,hunter.346@osu.edu,hunter.346@osu.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,Steven Fulkerson,Steven,Fulkerson,Vice President For Administration and Chief In...,Technology,University Of Arkansas System,UniversityOfArkansasSystem,universityofarkansassystem,"sfulkerson@areon.net, steven.fulkerson@gmail.c...",sfulkerson@areon.net,steven.fulkerson@gmail.com,stevenfulkerson@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,Sam Segran,Sam,Segran,Chief Information Officer,Education,Texas Tech University,TexasTechUniversity,texastechuniversity,"sam.segran@ttu.edu, segran@yahoo.com",sam.segran@ttu.edu,segran@yahoo.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
file_name = 'NotMatched.xlsx'
df22.to_excel(file_name)

In [122]:
xls = pd.ExcelFile('Fastbase_business_contacts_excel_699_HVVPQG.xlsx')
df30 = pd.read_excel(xls, 'Leads_search_02')

In [123]:
df30

,FULL NAME,First Name,Last Name,JOB TITLE,CITY,COUNTRY,EMAIL,COMPANY NAME,COMPANY LOCATION,COMPANY CATEGORY
0,Jeri Dunn,Jeri,Dunn,Senior Vice President and Chief Information Of...,Lowell,United States,jeri.dunn@tyson.com,Tyson Foods,"Springdale, Arkansas, United States",Food Production
1,Jim Onalfo,Jim,Onalfo,Chief Information Officer,New York,United States,jonalfo@aol.com,Nypd,"New York, New York, United States",Government Administration
2,James Benton,James,Benton,Chief Information Officer,Arlington,United States,"james.benton@pae.com, jamesbenton@a-tsolutions...",Pae,"Falls Church, Virginia, United States",International Trade and Development
3,Terry Phillis,Terry,Phillis,Chief Information Officer at City of Philadelphia,Philadelphia,United States,"terry.phillis@phila.gov, terry.m.phillis@phila...",City Of Philadelphia,"Philadelphia, Pennsylvania, United States",Government Administration
4,Dale Jablonsky,Dale,Jablonsky,Chief Information Officer Advisory Director,Sacramento,United States,"dale_jablonsky@calpers.ca.gov, djablons75@gmai...",Kpmg,"Toronto, Ontario, Canada",Government Administration
...,...,...,...,...,...,...,...,...,...,...
609,Vincent Piccinni,Vincent,Piccinni,Deputy Secretariet Chief Information Officer,Revere,United States,"vincent.piccinni@mass.gov, vpiccinni@hotmail.com",Commonwealth Of Massachusetts,"Boston, Massachusetts, United States",Government Administration
610,Damon Frost,Damon,Frost,Director - Skin and Personal Care Chief Inform...,Cincinnati,United States,frost.dl@pg.com,Procter & Gamble,"Cincinnati, Ohio, United States",Consumer Goods
611,Mindy Simon,Mindy,Simon,Chief Information Officer Global Business and ...,Omaha,United States,mindy.simon@conagrafoods.com,Conagra Foods,"Chicago, Illinois, United States",Consumer Goods
612,Joe Dumara,Joe,Dumara,Chief Information Officer,Ocala,United States,"joe.dumara@deere.com, jdumara@deere.com",John Deere Agri Services,United States,Automotive
613,Nada Daman,Nada,Daman,Business Value Realization Coach and Consultan...,Allen Park,United States,"ndaman@ford.com, nadasdaman@yahoo.com",Ford Motor Company,"Dearborn, Michigan, United States",Automotive

In [124]:
file_name = 'Leads_search2.xlsx'
df30.to_excel(file_name)