In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel("Healthcare-Pharma-Research-Consulting-Transportation.xlsx")

In [3]:
df

,Contact Name,First Name,Last Name,Email,Title,Company Name,Address,City,State,Zip Code,Country,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry
0,Tony Thomas,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,802 Sharon Dr Ste A,Westlake,Ohio,44145-1539,United States,+1-440-356-2330,NaN,www.welcomehouseinc.org,50M - 100M,250 - 500,Healthcare
1,Krystal Hadaway,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",3340 Hospital Rd,Saginaw,Michigan,48603-9622,United States,+1-989-790-7700,NaN,www.healthsourcesaginaw.org,50M - 100M,250 - 500,Healthcare
2,Kate Mccann,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,155 Wilson Ave,Washington,Pennsylvania,15301-3398,United States,+1-724-225-7000,NaN,www.whs.org,246M,NaN,Healthcare
3,Sheila Lambert,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,411 N Belknap St,Stephenville,Texas,76401-3415,United States,+1-254-965-1500,NaN,www.texashealth.org,100M - 250M,500 - 1000,Healthcare
4,Laura Honeycutt,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",607 Beaman St,Clinton,North Carolina,28328-2603,United States,+1-910-592-8511,NaN,www.sampsonrmc.org,100M - 250M,500 - 1000,Healthcare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12272,Juan Montalvo,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,1400 Douglas St Stop 1230,Omaha,Nebraska,68179-1001,United States,+1-402-544-7094,NaN,www.upds.com,50M - 100M,250 - 500,Transportation
12273,Scott Jay,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,120 E Harris Ave,San Angelo,Texas,76903-5976,United States,+1-325-653-6741,NaN,www.shannonhealth.com,306M,1.5k,Healthcare
12274,David Horak,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",122 E College Ave Ste 2A,Appleton,Wisconsin,54911-5741,United States,+1-920-735-5560,NaN,www.thedacare.org,995M,NaN,Healthcare
12275,Amber Crum,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",1300 Miccosukee Rd,Tallahassee,Florida,32308-5037,United States,+1-850-431-1155,NaN,www.tmh.org,648M,NaN,Healthcare
12276,Olga Modders,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",3231 Sw 34Th Ave,Ocala,Florida,34474-8489,United States,+1-352-873-7400,NaN,www.hospiceofmarion.com,50M - 100M,250 - 500,Healthcare

In [4]:
df1 = df.drop(['Contact Name','Address','City','State','Zip Code','Country','Fax Number','Web Site','Revenue'],axis='columns')
df1.shape

(12277, 8)

In [5]:
df1.describe()

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry
count,12277,12277,12277,12277,12277,12271,9866,12277
unique,2810,8082,12277,9,5188,4995,368,5
top,John,Smith,tthomas@welcomehouseinc.org,Learning and Development Manager,"Bdp International, Inc.",+1-281-618-3100,250 - 500,Healthcare
freq,192,73,1,2434,8,12,5390,6637

In [13]:
if df1.isnull().sum().any()>0:
    print("True")

True

In [7]:
df1.isnull()

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
12272,False,False,False,False,False,False,False,False
12273,False,False,False,False,False,False,False,False
12274,False,False,False,False,False,False,True,False
12275,False,False,False,False,False,False,True,False
12276,False,False,False,False,False,False,False,False

In [184]:
df1['Industry'] = df1['Industry'].replace(['Pharma'],'Healthcare')

In [185]:
df1['Industry'] = df1['Industry'].replace(['Research'],'Healthcare')

In [186]:
df1['Industry'] = df1['Industry'].replace(['Consulting'],'Professional Services')

In [187]:
df1

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare
2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare
3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare
4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare
...,...,...,...,...,...,...,...,...
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation
12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare
12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare
12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare

In [188]:
df1['Industry'].unique()

array(['Healthcare', 'Transportation', 'Professional Services'],
      dtype=object)

In [189]:
print(df1['Employees'].unique())

['250 - 500' nan '500 - 1000' '2.1k' '800' '6.5k' '2k' '300' '160' '29k'
 '8k' '850' '3k' '3.4k' '720' '900' '450' '16k' '1.1k' '25k' '2.5k' '515'
 '4k' '280' '13k' '6.4k' '2.4k' '210' '3.5k' '881' '14k' '342k' '725'
 '249' '4.1k' '6.1k' '520' '653' '4.5k' '100' '2.2k' '55k' '320' '5.5k'
 '107' '975' '200' '6k' '113k' '1.5k' '1.7k' '3.2k' '500' '400' '1.3k'
 '1k' '4.7k' '2.6k' '24k' '690' '570' '4.4k' '9.3k' '166' '201' '480'
 '660' '280k' '3.3k' '170' '600' '21k' '1.2k' '350' '474' '66k' '5k' '42k'
 '90k' '7.8k' '129' '2.7k' '9k' '654' '4.9k' '402' '20k' '840' '85k' '444'
 '760' '386' '10k' '591' '12k' '18k' '37k' '950' '825' '7k' '435' '11k'
 '892' '639' '412' '535' '687' '1.4k' '2.3k' '700' '64k' '432' '1.8k'
 '8.6k' '645' '891' '651' '4.8k' '610' '880' '382' '23k' '2.8k' '295'
 '650' '15k' '177' '19k' '420' '5.9k' '309' '618' '372' '1.6k' '749'
 '1.9k' '360' '532' '178' '232' '5.3k' '130' '5.1k' '240' '377' '62k'
 '40k' '60k' '703' '395' '120' '885' '275' '640' '150' '100k' '236' '985'
 '857' '616' '940' '499' '440' '620' '275k' '5.6k' '4.2k' '53k' '448'
 '506' '878' '35k' '737' '750' '417' '775' '502' '903' '208' '944' '681'
 '125' '870' '815' '17k' '8.9k' '141' '39k' '587' '4.6k' '949' '190' '305'
 '220' '250' '437' '505' '414' '780' '140' '4.3k' '6.3k' '336' '460' '476'
 '673' '575' '3.8k' '479' '983' '176' '109k' '649' '495' '728' '699'
 '3.1k' '990' '467' '902' '390' '670' '200k' '425' '380' '405' '7.4k'
 '330' '818' '7.6k' '603' '625' '34k' '3.6k' '890' '26k' '456' '550' '688'
 '980' '8.3k' '947' '310' '30k' '46k' '685' '9.1k' '805' '138k' '626'
 '765' '347' '255' '2.9k' '290k' '8.8k' '755' '576' '545' '525' '225'
 '540' '657' '33k' '675' '57k' '329' '864' '31k' '7.5k' '253k' '58k'
 '3.9k' '244' '486' '716' '477' '67k' '7.1k' '80k' '485' '986' '622' '465'
 '318' '548' '586' '6.6k' '135' '430' '726' '777' '629' '798' '8.5k'
 '8.2k' '3.7k' '768' '779' '945' '298' '28k' '585' '114' '995' '122'
 '107k' '139' '136' '304' '241' '171' '580' '345' '235' '796' '41k' '112'
 '927' '6.7k' '5.4k' '353' '209' '175' '628' '119' '65k' '6.2k' '659'
 '158' '185' '180' '481' '340' '325' '172' '735' '8.1k' '52k' '252' '458'
 '542' '7.3k' '678' '132k' '218' '131' '101' '451' '167' '875' '484' '533'
 '230' '406' '521' '613' '607' '5.8k' '528' '470' '352' '497' '6.8k' '534'
 '517' '285' '976' '930']

In [190]:
df2=df1

In [191]:
df2

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare
2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare
3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare
4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare
...,...,...,...,...,...,...,...,...
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation
12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare
12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare
12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare

In [192]:
df2['Employees_New']=df2['Employees']

In [193]:
df2

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare,250 - 500
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare,250 - 500
2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare,NaN
3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare,500 - 1000
4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare,500 - 1000
...,...,...,...,...,...,...,...,...,...
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation,250 - 500
12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare,1.5k
12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare,NaN
12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare,NaN
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare,250 - 500

In [194]:
df2.Employees_New = df2.Employees_New.fillna('10000000000')

In [195]:
df2.isnull().sum()

First Name          0
Last Name           0
Email               0
Title               0
Company Name        0
Phone Number        6
Employees        2411
Industry            0
Employees_New       0
dtype: int64

In [196]:
df2

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare,250 - 500
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare,250 - 500
2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare,10000000000
3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare,500 - 1000
4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare,500 - 1000
...,...,...,...,...,...,...,...,...,...
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation,250 - 500
12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare,1.5k
12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare,10000000000
12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare,10000000000
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare,250 - 500

In [197]:
def convert_employees(x):
    if '-' in x:
        tokens = x.split('-')
        return (float(tokens[1]))
    elif 'k' in x:
        tokens =x.split('k')
        return float(tokens[0])*1000
    else:
        return float(x)

In [198]:
df2.Employees_New = df2.Employees_New.apply(convert_employees)

In [199]:
df2

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare,5.000000e+02
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare,5.000000e+02
2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare,1.000000e+10
3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare,1.000000e+03
4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare,1.000000e+03
...,...,...,...,...,...,...,...,...,...
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation,5.000000e+02
12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare,1.500000e+03
12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare,1.000000e+10
12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare,1.000000e+10
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare,5.000000e+02

In [200]:
df2.drop(df2[df2['Employees_New'] > 500].index, inplace = True)

In [201]:
df2

,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare,500.0
1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare,500.0
7,Dontai,Nash,dontai.nash@walmart.com,Learning and Development Manager,"Wal-Mart Transportation, LLC",+1-479-273-4000,250 - 500,Transportation,500.0
8,Bryan,Munchel,bmunchel@postacutemedical.com,CIO,"Post Acute Medical, LLC",+1-717-731-9660,250 - 500,Healthcare,500.0
9,Rebecca,Baxter,rebecca_baxter@flpps.org,L&D Manager,"Finger Lakes Performing Provider System, Inc.",+1-585-239-9308,250 - 500,Professional Services,500.0
...,...,...,...,...,...,...,...,...,...
12265,Kimberly,Anthony,kimberly.anthony@aprevahospice.com,Learning and Development Director,Apreva Corporation,+1-619-450-4414,250 - 500,Healthcare,500.0
12267,Lorrie,Roddy,lroddy@intlfreight.net,Director Of Learning and Development,"Edward J. Zarach & Associates, Inc.",+1-630-595-7300,250 - 500,Transportation,500.0
12270,Krietsch,Michelle,michelle_krietsch@apllogistics.com,Learning and Development Manager,GATX Logistics Inc,+1-336-306-8376,250 - 500,Transportation,500.0
12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation,500.0
12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare,500.0

In [202]:
file_name = 'less than five hundred.xlsx'
df2.to_excel(file_name)

In [19]:
df10=pd.read_excel("greater than five hundred.xlsx")

In [20]:
df10

,Unnamed: 0,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,2,Kate,Mccann,kmccann@washingtonhospital.org,Learning and Development Director,The Washington Hospital,+1-724-225-7000,NaN,Healthcare,10000000000
1,3,Sheila,Lambert,sheilalambert@texashealth.org,Learning and Development Manager,Texas Health Harris Methodist Hospital Stephen...,+1-254-965-1500,500 - 1000,Healthcare,1000
2,4,Laura,Honeycutt,lhoneycutt@sampsonrmc.org,Learning and Development Director,"Sampson Regional Medical Center, Incorporated",+1-910-592-8511,500 - 1000,Healthcare,1000
3,5,Warren,Robinson,wrobinson@mauryregional.com,Learning & Development Supervisor,Maury Regional Hospital,+1-931-381-1111,2.1k,Healthcare,2100
4,6,Tara,Gilroy,tgilroy@mvhealthsystem.org,Learning and Development Manager,Faxton-St. Luke's Healthcare,+1-315-624-6000,NaN,Healthcare,10000000000
...,...,...,...,...,...,...,...,...,...,...
6312,12269,Rachel,Money,rmoney@iuhealth.org,Learning & Development Supervisor,"Indiana University Health Bloomington, Inc.",+1-812-353-5252,3.2k,Healthcare,3200
6313,12271,Joseph,Rudolph,josephr@ccf.org,Manager of Learning & Development,The Cleveland Clinic Foundation,+1-216-636-8335,NaN,Healthcare,10000000000
6314,12273,Scott,Jay,scottjay@shannonhealth.org,Learning & Development Supervisor,Shannon Medical Center,+1-325-653-6741,1.5k,Healthcare,1500
6315,12274,David,Horak,david.horak@thedacare.org,CIO,"Thedacare, Inc.",+1-920-735-5560,NaN,Healthcare,10000000000
6316,12275,Amber,Crum,amber.crum@tmh.org,Learning and Development Director,"Tallahassee Memorial Healthcare, Inc.",+1-850-431-1155,NaN,Healthcare,10000000000

In [21]:
df11 = df10.drop(df10[(df10['Industry'] == 'Healthcare') | (df10['Industry'] == 'Transportation')].index)

In [22]:
df11

,Unnamed: 0,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
14,28,Tyler,Lummis,tlummis@deloitte.com,Learning and Development Manager,Deloitte Consulting LLP,+1-212-492-4000,6.5k,Professional Services,6500
31,58,John,Kim,john.kim@adpt.com,Manager of Learning & Development,Adeptus Health Inc.,+1-972-899-6666,NaN,Professional Services,10000000000
40,74,Adam,Olivares,adam.olivares@adpt.com,Learning & Development Supervisor,Adeptus Health Inc.,+1-972-899-6666,NaN,Professional Services,10000000000
44,79,Kamie,Sickels,sickelk@sutterhealth.org,Learning and Development Manager,Sutter Physician Services,+1-916-854-6600,500 - 1000,Professional Services,1000
83,160,Zach,Savage,zsavage@westmonroepartners.com,L&D Manager,"West Monroe Partners, LLC",+1-312-602-4000,500 - 1000,Professional Services,1000
...,...,...,...,...,...,...,...,...,...,...
6108,11877,Darlene,Hawkins,darlene.hawkins@leonagroup.com,Learning and Development Manager,The Leona Group L L C,+1-517-333-9030,500 - 1000,Professional Services,1000
6286,12225,Atiq,Abdullah,atiq.abdullah@akqa.com,Learning & Development Supervisor,"Akqa, Inc.",+1-415-645-9400,500 - 1000,Professional Services,1000
6293,12237,David,Zakson,david.zakson@westmonroepartners.com,Manager of Learning & Development,"West Monroe Partners, LLC",+1-312-602-4000,500 - 1000,Professional Services,1000
6294,12240,Elaine,Cheung,elaine.cheung@multiplan.com,Manager of Learning & Development,"Multiplan, Inc.",+1-212-780-2000,506,Professional Services,506
6302,12252,Bob,Chess,bchess@acrtinc.com,Director Of Learning and Development,"Acrt, Inc.",+1-800-622-2562,500 - 1000,Professional Services,1000

In [12]:
df40=pd.read_excel("less than five hundred.xlsx")

In [13]:
df40

,Unnamed: 0,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
0,0,Tony,Thomas,tthomas@welcomehouseinc.org,CIO,Welcome House Inc,+1-440-356-2330,250 - 500,Healthcare,500
1,1,Krystal,Hadaway,ktebedo@healthsourcesaginaw.org,Director Of Learning and Development,"Healthsource Saginaw, Inc.",+1-989-790-7700,250 - 500,Healthcare,500
2,7,Dontai,Nash,dontai.nash@walmart.com,Learning and Development Manager,"Wal-Mart Transportation, LLC",+1-479-273-4000,250 - 500,Transportation,500
3,8,Bryan,Munchel,bmunchel@postacutemedical.com,CIO,"Post Acute Medical, LLC",+1-717-731-9660,250 - 500,Healthcare,500
4,9,Rebecca,Baxter,rebecca_baxter@flpps.org,L&D Manager,"Finger Lakes Performing Provider System, Inc.",+1-585-239-9308,250 - 500,Professional Services,500
...,...,...,...,...,...,...,...,...,...,...
5955,12265,Kimberly,Anthony,kimberly.anthony@aprevahospice.com,Learning and Development Director,Apreva Corporation,+1-619-450-4414,250 - 500,Healthcare,500
5956,12267,Lorrie,Roddy,lroddy@intlfreight.net,Director Of Learning and Development,"Edward J. Zarach & Associates, Inc.",+1-630-595-7300,250 - 500,Transportation,500
5957,12270,Krietsch,Michelle,michelle_krietsch@apllogistics.com,Learning and Development Manager,GATX Logistics Inc,+1-336-306-8376,250 - 500,Transportation,500
5958,12272,Juan,Montalvo,jpmontal@up.com,Learning and Development Manager,Loup Logistics Company,+1-402-544-7094,250 - 500,Transportation,500
5959,12276,Olga,Modders,omodders@hospiceofmarion.com,L&D Manager,"Hospice of Marion County, Inc.",+1-352-873-7400,250 - 500,Healthcare,500

In [14]:
df41 = df40.drop(df40[(df40['Industry'] == 'Transportation') | (df40['Industry'] == 'Healthcare')].index)

In [15]:
df41

,Unnamed: 0,First Name,Last Name,Email,Title,Company Name,Phone Number,Employees,Industry,Employees_New
4,9,Rebecca,Baxter,rebecca_baxter@flpps.org,L&D Manager,"Finger Lakes Performing Provider System, Inc.",+1-585-239-9308,250 - 500,Professional Services,500
37,90,Liz,Nannen,l.nannen@strategichs.com,Learning and Development Manager,"Strategichealthsolutions, LLC",+1-402-452-3333,250 - 500,Professional Services,500
46,110,Paul,Waters,pwaters@waltoncommunities.com,Manager of Learning & Development,"Walton Communities, LLC",+1-678-303-4100,250 - 500,Professional Services,500
49,114,Susan,Gowen,sgowen@ekhealth.com,Learning and Development Director,Ek Health Services Inc.,+1-408-973-888,250 - 500,Professional Services,500
51,116,Missy,Peyer,mpeyer@adreima.com,Learning and Development Manager,"Advanced Reimbursement Management, LLC",+1-602-636-5500,250 - 500,Professional Services,500
...,...,...,...,...,...,...,...,...,...,...
5897,12143,Masako,Cornett,masako.cornett@pacgroup.com,Director Of Learning and Development,"Pac Project Advisors International, Ltd.",+1-248-643-3800,250 - 500,Professional Services,500
5899,12146,Cynthia,Martinez,cmartinez@powerwellness.com,Learning and Development Director,Wellness Power Management LLC,+1-630-570-2600,250 - 500,Professional Services,500
5906,12156,Barbara,Lewer,barbara.lewer@omvmedical.com,Head Of L&D,Omv Medical Inc.,+1-301-270-9212,250 - 500,Professional Services,500
5922,12185,Jeremy,Preston,jdpreston@dow.com,Learning & Development Supervisor,The Dow Chemical Company Foundation,+1-989-636-1000,250 - 500,Professional Services,500
5940,12229,Michael,Bowe,michaelb@resourceone-llc.com,CIO,Resource One Medical Billing,+1-803-765-1838,250 - 500,Professional Services,500

In [16]:
file_name = 'Professional Services.xlsx'
df41.to_excel(file_name)

In [3]:
df50=pd.read_excel("Healthcare-Research-Transportation-Data-Snap-List-2.xlsx")

TypeError: read_excel() got an unexpected keyword argument 'sheet'

In [37]:
df50

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry
0,Steven Heiman,Steven,Heiman,sheiman@matherhospital.org,"Head, Learning and Development",Mather Hospital,+1-216-844-7890,+1-216-844-1632,www.matherhospital.org,$500M - $1B,">10,000",Healthcare
1,Ed Ricks,Ed,Ricks,ericks@bmhsc.org,Learning and Development Manager,Beaufort Memorial Hospital,+1-843-522-5200,NaN,www.bmhsc.org,$500M - $1B,">10,000",Healthcare
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Pharma
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation
4,Karine Aylozyan,Karine,Aylozyan,karine@microqualitylabs.com,Learning and Development Manager,Micro Quality Labs Inc,+1-818-845-0070,+1-818-845-0030,www.microqualitylabs.com,$25M - $50M,">10,000",Pharma
...,...,...,...,...,...,...,...,...,...,...,...,...
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare
4854,Jo Convis,Jo,Convis,jconvis@sjgh.org,"Head, Learning and Development",San Joaquin General Hospital,+1-209-468-6000,+1-209-468-6246,www.sjgh.org,$100 - 250M,">10,000",Healthcare
4855,Matthew Fine,Matthew,Fine,mfine@orohosp.com,Learning and Development Manager,Oroville Hospital,+1-530-533-8500,+1-530-538-3117,www.orohosp.com,$250 - 500M,">10,000",Healthcare
4856,Ying D Higgins,Ying,Higgins,yhiggins@amerihealthcaritas.com,Learning & Development Supervisor,Amerihealth Caritas,+1-215-937-8000,NaN,www.amerihealthcaritas.com,$1B,"> 10,000",Healthcare
4857,Phil Dougan,Phil,Dougan,phil.dougan@pdisrd.com,Learning and Development Manager,"Perishable Distributors Of Iowa, Ltd.",+1-515-965-6300,NaN,www.contactpdi.com,$250M - $500M,"5,000 - 10,000",Transportation

In [38]:
df50['Industry'].unique()

array(['Healthcare', 'Pharma', 'Transportation'], dtype=object)

In [39]:
df50['Industry'] = df50['Industry'].replace(['Pharma'],'Healthcare')

In [40]:
print(df50['Employees'].unique())

['>10,000' '1,000 - 5,000' '2K - 10K' '> 10,000' '5,000 - 10,000'
 '1,000-5,000' '1,380' '1K - 10K' '1,000 - 2,500' '50K - 100K' '5,000'
 '10,000' '> 1,000' 'Over 10,000' '10K - 50K' '3,000' '1,000 - 2000'
 '6,000' '>1,000' '> 100K' '2,500 - 5,000' '2,340' '1,000' '2,000 - 4,000'
 '2,000' '5000 - 10,000' '9,070' '6,100' '1,000 - $5,000' '1,395'
 '5,000 - 7,500' '59,076' '58,000' '1,539' '2,670' '100 - 5,000' '1,980'
 '5,000-10,000' '3,900' '10,800' '1,445' '6,342' '1,550' '7,299' '1,200'
 '9,800' '19,000' 'Over10,000' '3,650' '2,300' '80,723' 1000]

In [41]:
df50.isnull().sum()

Contact Name       0
First Name         0
Last Name          0
Email              0
Title              0
Company Name       0
Phone Number       0
Fax Number      1760
Web Site           0
Revenue          970
Employees          0
Industry           0
dtype: int64

In [42]:
df51=df50

In [43]:
df51['Employees_New']=df51['Employees']

In [44]:
df51

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Employees_New
0,Steven Heiman,Steven,Heiman,sheiman@matherhospital.org,"Head, Learning and Development",Mather Hospital,+1-216-844-7890,+1-216-844-1632,www.matherhospital.org,$500M - $1B,">10,000",Healthcare,">10,000"
1,Ed Ricks,Ed,Ricks,ericks@bmhsc.org,Learning and Development Manager,Beaufort Memorial Hospital,+1-843-522-5200,NaN,www.bmhsc.org,$500M - $1B,">10,000",Healthcare,">10,000"
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Healthcare,"1,000 - 5,000"
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,"1,000 - 5,000"
4,Karine Aylozyan,Karine,Aylozyan,karine@microqualitylabs.com,Learning and Development Manager,Micro Quality Labs Inc,+1-818-845-0070,+1-818-845-0030,www.microqualitylabs.com,$25M - $50M,">10,000",Healthcare,">10,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,"1,000 - 5,000"
4854,Jo Convis,Jo,Convis,jconvis@sjgh.org,"Head, Learning and Development",San Joaquin General Hospital,+1-209-468-6000,+1-209-468-6246,www.sjgh.org,$100 - 250M,">10,000",Healthcare,">10,000"
4855,Matthew Fine,Matthew,Fine,mfine@orohosp.com,Learning and Development Manager,Oroville Hospital,+1-530-533-8500,+1-530-538-3117,www.orohosp.com,$250 - 500M,">10,000",Healthcare,">10,000"
4856,Ying D Higgins,Ying,Higgins,yhiggins@amerihealthcaritas.com,Learning & Development Supervisor,Amerihealth Caritas,+1-215-937-8000,NaN,www.amerihealthcaritas.com,$1B,"> 10,000",Healthcare,"> 10,000"
4857,Phil Dougan,Phil,Dougan,phil.dougan@pdisrd.com,Learning and Development Manager,"Perishable Distributors Of Iowa, Ltd.",+1-515-965-6300,NaN,www.contactpdi.com,$250M - $500M,"5,000 - 10,000",Transportation,"5,000 - 10,000"

In [46]:
#x='1K - 10K'
#x1='1,000 - 5,000'
x2='1,000 - $5,000'
l=x2.split('-')
#for i in l:
 #   print(i)
f=l[1].strip()  
final=f.split('$')
final1=(final[1])
eval(final1)

(5, 0)

In [47]:
z='5,000'
eval(z)

(5, 0)

In [25]:
y='>10,000'
tokens=y.split('>')

ValueError: could not convert string to float: '10,000'

In [ ]:
def convert_employees(x):
    if 'K' in x:
        tokens = x.split('K')
        if 'K' in f:
            final=f.split('K')
            return float(final[0])
    elif '>' in x:
        tokens =x.split('>')
        return float(tokens[0])*1000
    else:
        return float(x)

In [ ]:
df2.Employees_New = df2.Employees_New.apply(convert_employees)

In [60]:
xls = pd.ExcelFile('Healthcare-Research-Transportation-Data-Snap-List-2.xlsx')
df70 = pd.read_excel(xls, 'Sheet1')

In [61]:
df70

,Employees,Unnamed: 1,Extracted,Employees0,Unnamed: 4,Employees1,Unnamed: 6,Emplyees_Final,Emp
0,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
1,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
2,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000
3,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000
4,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
...,...,...,...,...,...,...,...,...,...
4853,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000
4854,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
4855,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
4856,"> 10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000
4857,"5,000 - 10,000",NaN,"10,000","5,000 - 10,000",NaN,5000,10000,10000,10000

In [62]:
df70.isnull().sum()

Employees            0
Unnamed: 1        4858
Extracted            0
Employees0        2237
Unnamed: 4        2621
Employees1        2237
Unnamed: 6        2452
Emplyees_Final       0
Emp                  0
dtype: int64

In [63]:
print(df70['Emp'].unique())

['10000' '5000' '10K' '1380' '2500' '100K' '1000' '100000000' '50K' '3000'
 '2000' '6000' '2340' '4000' '9070' '6100' '1395' '7500' '59076' '58000'
 '1539' '2670' '1980' '3900' '10800' '1445' '6342' '1550' '7299' '1200'
 '9800' '19000' '3650' '2300' '80723']

In [37]:
df70['Emplyees_Final'] = df70['Emplyees_Final'].replace([' $5,000'],5000)

In [52]:
print(df70['Emp'].unique())

['10000' '5000' '10K' '1380' '2500' '100K' '1000' '100000000' '50K' '3000'
 '2000' '6000' '2340' '4000' '9070' '6100' '1395' '7500' '59076' '58000'
 '1539' '2670' '1980' '3900' '10800' '1445' '6342' '1550' '7299' '1200'
 '9800' '19000' '3650' '2300' '80723']

In [64]:
def convert_employees(x):
    try:
        if 'K' in x:
            tokens = x.split('K')
            return float(tokens[0])*1000
        else:
            return float(x)
    except:    
        return float(x)

In [59]:
a='10K'
b=a.split('K')
e=int(b[0]*1000)
e

10101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010

In [65]:
df70.Emp = df70.Emp.apply(convert_employees)

In [66]:
df70

,Employees,Unnamed: 1,Extracted,Employees0,Unnamed: 4,Employees1,Unnamed: 6,Emplyees_Final,Emp
0,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
1,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
2,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
3,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
4,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
...,...,...,...,...,...,...,...,...,...
4853,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
4854,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4855,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4856,"> 10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4857,"5,000 - 10,000",NaN,"10,000","5,000 - 10,000",NaN,5000,10000,10000,10000.0

In [67]:
print(df70['Emp'].unique())

[1.0000e+04 5.0000e+03 1.3800e+03 2.5000e+03 1.0000e+05 1.0000e+03
 1.0000e+08 5.0000e+04 3.0000e+03 2.0000e+03 6.0000e+03 2.3400e+03
 4.0000e+03 9.0700e+03 6.1000e+03 1.3950e+03 7.5000e+03 5.9076e+04
 5.8000e+04 1.5390e+03 2.6700e+03 1.9800e+03 3.9000e+03 1.0800e+04
 1.4450e+03 6.3420e+03 1.5500e+03 7.2990e+03 1.2000e+03 9.8000e+03
 1.9000e+04 3.6500e+03 2.3000e+03 8.0723e+04]

In [68]:
df70

,Employees,Unnamed: 1,Extracted,Employees0,Unnamed: 4,Employees1,Unnamed: 6,Emplyees_Final,Emp
0,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
1,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
2,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
3,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
4,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
...,...,...,...,...,...,...,...,...,...
4853,"1,000 - 5,000",NaN,"5,000","1,000 - 5,000",NaN,1000,5000,5000,5000.0
4854,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4855,">10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4856,"> 10,000",NaN,"10,000",NaN,10000,NaN,NaN,10000,10000.0
4857,"5,000 - 10,000",NaN,"10,000","5,000 - 10,000",NaN,5000,10000,10000,10000.0

In [69]:
file_name = 'Emp_Final.xlsx'
df70.to_excel(file_name)

In [46]:
df=pd.read_excel("Healthcare-Research-Transportation-Data-Snap-List-2.xlsx")

In [47]:
df

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
0,Steven Heiman,Steven,Heiman,sheiman@matherhospital.org,"Head, Learning and Development",Mather Hospital,+1-216-844-7890,+1-216-844-1632,www.matherhospital.org,$500M - $1B,">10,000",Healthcare,10000
1,Ed Ricks,Ed,Ricks,ericks@bmhsc.org,Learning and Development Manager,Beaufort Memorial Hospital,+1-843-522-5200,NaN,www.bmhsc.org,$500M - $1B,">10,000",Healthcare,10000
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Pharma,5000
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
4,Karine Aylozyan,Karine,Aylozyan,karine@microqualitylabs.com,Learning and Development Manager,Micro Quality Labs Inc,+1-818-845-0070,+1-818-845-0030,www.microqualitylabs.com,$25M - $50M,">10,000",Pharma,10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,5000
4854,Jo Convis,Jo,Convis,jconvis@sjgh.org,"Head, Learning and Development",San Joaquin General Hospital,+1-209-468-6000,+1-209-468-6246,www.sjgh.org,$100 - 250M,">10,000",Healthcare,10000
4855,Matthew Fine,Matthew,Fine,mfine@orohosp.com,Learning and Development Manager,Oroville Hospital,+1-530-533-8500,+1-530-538-3117,www.orohosp.com,$250 - 500M,">10,000",Healthcare,10000
4856,Ying D Higgins,Ying,Higgins,yhiggins@amerihealthcaritas.com,Learning & Development Supervisor,Amerihealth Caritas,+1-215-937-8000,NaN,www.amerihealthcaritas.com,$1B,"> 10,000",Healthcare,10000
4857,Phil Dougan,Phil,Dougan,phil.dougan@pdisrd.com,Learning and Development Manager,"Perishable Distributors Of Iowa, Ltd.",+1-515-965-6300,NaN,www.contactpdi.com,$250M - $500M,"5,000 - 10,000",Transportation,10000

In [48]:
df['Industry'] = df['Industry'].replace(['Pharma'],'Healthcare')

In [49]:
df

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
0,Steven Heiman,Steven,Heiman,sheiman@matherhospital.org,"Head, Learning and Development",Mather Hospital,+1-216-844-7890,+1-216-844-1632,www.matherhospital.org,$500M - $1B,">10,000",Healthcare,10000
1,Ed Ricks,Ed,Ricks,ericks@bmhsc.org,Learning and Development Manager,Beaufort Memorial Hospital,+1-843-522-5200,NaN,www.bmhsc.org,$500M - $1B,">10,000",Healthcare,10000
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
4,Karine Aylozyan,Karine,Aylozyan,karine@microqualitylabs.com,Learning and Development Manager,Micro Quality Labs Inc,+1-818-845-0070,+1-818-845-0030,www.microqualitylabs.com,$25M - $50M,">10,000",Healthcare,10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,5000
4854,Jo Convis,Jo,Convis,jconvis@sjgh.org,"Head, Learning and Development",San Joaquin General Hospital,+1-209-468-6000,+1-209-468-6246,www.sjgh.org,$100 - 250M,">10,000",Healthcare,10000
4855,Matthew Fine,Matthew,Fine,mfine@orohosp.com,Learning and Development Manager,Oroville Hospital,+1-530-533-8500,+1-530-538-3117,www.orohosp.com,$250 - 500M,">10,000",Healthcare,10000
4856,Ying D Higgins,Ying,Higgins,yhiggins@amerihealthcaritas.com,Learning & Development Supervisor,Amerihealth Caritas,+1-215-937-8000,NaN,www.amerihealthcaritas.com,$1B,"> 10,000",Healthcare,10000
4857,Phil Dougan,Phil,Dougan,phil.dougan@pdisrd.com,Learning and Development Manager,"Perishable Distributors Of Iowa, Ltd.",+1-515-965-6300,NaN,www.contactpdi.com,$250M - $500M,"5,000 - 10,000",Transportation,10000

In [50]:
df1=df

In [51]:
df1.drop(df1[df1['Emp'] <5000].index, inplace = True) #under 5k
#df2.drop(df2[df2['Employees_New'] > 500].index, inplace = True)

In [52]:
df1

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
0,Steven Heiman,Steven,Heiman,sheiman@matherhospital.org,"Head, Learning and Development",Mather Hospital,+1-216-844-7890,+1-216-844-1632,www.matherhospital.org,$500M - $1B,">10,000",Healthcare,10000
1,Ed Ricks,Ed,Ricks,ericks@bmhsc.org,Learning and Development Manager,Beaufort Memorial Hospital,+1-843-522-5200,NaN,www.bmhsc.org,$500M - $1B,">10,000",Healthcare,10000
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
4,Karine Aylozyan,Karine,Aylozyan,karine@microqualitylabs.com,Learning and Development Manager,Micro Quality Labs Inc,+1-818-845-0070,+1-818-845-0030,www.microqualitylabs.com,$25M - $50M,">10,000",Healthcare,10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,5000
4854,Jo Convis,Jo,Convis,jconvis@sjgh.org,"Head, Learning and Development",San Joaquin General Hospital,+1-209-468-6000,+1-209-468-6246,www.sjgh.org,$100 - 250M,">10,000",Healthcare,10000
4855,Matthew Fine,Matthew,Fine,mfine@orohosp.com,Learning and Development Manager,Oroville Hospital,+1-530-533-8500,+1-530-538-3117,www.orohosp.com,$250 - 500M,">10,000",Healthcare,10000
4856,Ying D Higgins,Ying,Higgins,yhiggins@amerihealthcaritas.com,Learning & Development Supervisor,Amerihealth Caritas,+1-215-937-8000,NaN,www.amerihealthcaritas.com,$1B,"> 10,000",Healthcare,10000
4857,Phil Dougan,Phil,Dougan,phil.dougan@pdisrd.com,Learning and Development Manager,"Perishable Distributors Of Iowa, Ltd.",+1-515-965-6300,NaN,www.contactpdi.com,$250M - $500M,"5,000 - 10,000",Transportation,10000

In [53]:
df1.drop(df1[df1['Emp'] >=10000].index, inplace = True)

In [60]:
df1

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
7,Brian L Helleland,Brian,Helleland,brian.helleland@stjoe.org,"Head, Learning and Development",St. Jude Medical Center,+1-714-871-3280,+1-714-447-6418,www.stjudemedicalcenter.com,NaN,"1,000 - 5,000",Healthcare,5000
8,James Pelliccio,James,Pelliccio,james.pelliccio@pnct.net,CIO,Port Newark Container Terminal,+1-973-522-2200,+1-973-465-8827,www.pnct.net,$500M - $1B,"1,000 - 5,000",Transportation,5000
9,Jenna Haymond,Jenna,Haymond,jhaymond@fhginc.com,Learning & Development Supervisor,"First Hospitality Group , Inc.",+1-757-496-6000,NaN,www.fhginc.com,$250M - $500M,"1,000 - 5,000",Healthcare,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4844,Sandra Kopacz,Sandra,Kopacz,skopacz@trhosp.org,"Head, Learning and Development",Taylor Regional Hospital,+1-270-465-3561,+1-478-892-3111,www.trhosp.org,NaN,"1,000 - 5,000",Healthcare,5000
4845,Penny O'Neill,Penny,O'Neill,penny_oneill@bshsi.org,Learning & Development Supervisor,"Bon Secours Health System, Inc.",+1-410-362-3000,+1-410-362-3130,www.bshsi.org,$250M - $500M,"1,000 - 5,000",Healthcare,5000
4847,Sheela Garudaiyengar,Sheela,Garudaiyengar,sgarudaiyengar@carecorenational.com,Learning & Development Supervisor,Carecore National,+1-800-918-8924,NaN,www.carecorenational.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
4850,Betsy Frost,Betsy,Frost,betsy.frost@capeair.com,Learning & Development Supervisor,Cape Air,+1-284-495-2100,+1-508-775-8815,www.capeair.com,$500M - $1B,"1,000 - 5,000",Transportation,5000
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,5000

In [61]:
df2=df1

In [62]:
df2

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
2,R P Balakumar,R,Balakumar,r.balakumar@sailife.com,Learning and Development Manager,Sai Life Sciences Ltd,+1-858-793-0400,NaN,www.sailife.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
7,Brian L Helleland,Brian,Helleland,brian.helleland@stjoe.org,"Head, Learning and Development",St. Jude Medical Center,+1-714-871-3280,+1-714-447-6418,www.stjudemedicalcenter.com,NaN,"1,000 - 5,000",Healthcare,5000
8,James Pelliccio,James,Pelliccio,james.pelliccio@pnct.net,CIO,Port Newark Container Terminal,+1-973-522-2200,+1-973-465-8827,www.pnct.net,$500M - $1B,"1,000 - 5,000",Transportation,5000
9,Jenna Haymond,Jenna,Haymond,jhaymond@fhginc.com,Learning & Development Supervisor,"First Hospitality Group , Inc.",+1-757-496-6000,NaN,www.fhginc.com,$250M - $500M,"1,000 - 5,000",Healthcare,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4844,Sandra Kopacz,Sandra,Kopacz,skopacz@trhosp.org,"Head, Learning and Development",Taylor Regional Hospital,+1-270-465-3561,+1-478-892-3111,www.trhosp.org,NaN,"1,000 - 5,000",Healthcare,5000
4845,Penny O'Neill,Penny,O'Neill,penny_oneill@bshsi.org,Learning & Development Supervisor,"Bon Secours Health System, Inc.",+1-410-362-3000,+1-410-362-3130,www.bshsi.org,$250M - $500M,"1,000 - 5,000",Healthcare,5000
4847,Sheela Garudaiyengar,Sheela,Garudaiyengar,sgarudaiyengar@carecorenational.com,Learning & Development Supervisor,Carecore National,+1-800-918-8924,NaN,www.carecorenational.com,$500M - $1B,"1,000 - 5,000",Healthcare,5000
4850,Betsy Frost,Betsy,Frost,betsy.frost@capeair.com,Learning & Development Supervisor,Cape Air,+1-284-495-2100,+1-508-775-8815,www.capeair.com,$500M - $1B,"1,000 - 5,000",Transportation,5000
4853,Katherine Lustila,Katherine,Lustila,klustila@lrmc.com,"Head, Learning and Development",Lakeland Regional Medical Center,+1-863-687-1100,+1-863-284-1892,www.lrmc.com,NaN,"1,000 - 5,000",Healthcare,5000

In [63]:
df3 = df2.drop(df2[(df2['Industry'] == 'Healthcare')].index) # This is for Transportation

In [64]:
df3

,Contact Name,First Name,Last Name,Email,Title,Company Name,Phone Number,Fax Number,Web Site,Revenue,Employees,Industry,Emp
3,Paul Slater,Paul,Slater,pslater@aimntls.com,CIO,Aim Nationalease,+1-215-744-0500,NaN,www.aimntls.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
8,James Pelliccio,James,Pelliccio,james.pelliccio@pnct.net,CIO,Port Newark Container Terminal,+1-973-522-2200,+1-973-465-8827,www.pnct.net,$500M - $1B,"1,000 - 5,000",Transportation,5000
15,Dana Hofer,Dana,Hofer,dhofer@mtm-inc.net,"Head, Learning and Development",Mtm Inc,+1-636-561-5686,+1-636-561-2962,www.mtm-inc.net,$250M - $500M,"1,000 - 5,000",Transportation,5000
70,Vicki Carmichael,Vicki,Carmichael,vickic@silversea.com,Learning and Development Manager,Silversea Cruises Ltd,+1-954-762-3485,+1-954-356-5881,www.silversea.com,$500M - $1B,"1,000 - 5,000",Transportation,5000
85,Julie Sieja,Julie,Sieja,jsieja@jackcooper.com,Learning and Development Manager,Jack Cooper Transport Co. Inc,+1-816-983-4000,+1-816-983-5020,www.jackcooper.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,Bob Vallandingham,Bob,Vallandingham,bvallandingham@superiorbulklogistics.com,"Head, Learning and Development",Superior Bulk Logistics Inc,+1-630-573-2555,+1-630-573-2570,www.superiorbulklogistics.com,$100M - $250M,"1,000 - 5,000",Transportation,5000
4814,Sam Crompton,Sam,Crompton,sam.crompton@nats.co.uk,Learning & Development Supervisor,Nats Limited,+1-860-635-6820,+1-860-635-4962,www.nats.co.uk,$1B - $5B,"1,000 - 5,000",Transportation,5000
4826,Doni Cornett,Doni,Cornett,doni.cornett@mesaba.com,Learning & Development Supervisor,Mesaba Airlines,+1-651-367-5000,+1-651-367-5392,www.mesaba.com,$100M - $250M,"1,000 - 5,000",Transportation,5000
4835,Carl Allen,Carl,Allen,carl.allen@horizonair.com,CIO,Horizon Air,+1-206-241-6757,+1-206-431-4696,www.horizonair.com,$250M - $500M,"1,000 - 5,000",Transportation,5000
4850,Betsy Frost,Betsy,Frost,betsy.frost@capeair.com,Learning & Development Supervisor,Cape Air,+1-284-495-2100,+1-508-775-8815,www.capeair.com,$500M - $1B,"1,000 - 5,000",Transportation,5000

In [65]:
file_name = 'Transportation_5kto10k.xlsx'
df3.to_excel(file_name)